#!/usr/bin/env python

import os
import uuid
import random
import time
import datetime

from twisted.internet import reactor, defer

from opennsa import nsa, setup



DYNAMICKL_SERVICE   = 'http://220.69.219.228:8010/nsi/ConnectionServiceProvider'
OPENNSA_SERVICE     = 'http://orval.grid.aau.dk:9080/NSI/services/ConnectionService'
LOCALHOST_SERVICE   = 'http://localhost:9080/NSI/services/ConnectionService'

ORVAL_REQUESTER     = 'http://orval.grid.aau.dk:7080/NSI/services/ConnectionService'
LOCAL_REQUESTER     = 'http://localhost:7080/NSI/services/ConnectionService'

HOST = 'localhost'
PORT = 7080


@defer.inlineCallbacks
def doMain():

    print 'OpenNSA WS test client'

    wsdl_dir =  os.path.join(os.path.dirname(os.path.abspath(__file__)), 'wsdl')

    client, service, factory = setup.createClient(HOST, PORT, wsdl_dir)

    reactor.listenTCP(PORT, factory)

    client_nsa      = nsa.NetworkServiceAgent('OpenNSA-testclient', LOCAL_REQUESTER)

    provider_local_aruba    = nsa.Network('Aruba',   nsa.NetworkServiceAgent('Aruba-OpenNSA', LOCALHOST_SERVICE))
    provider_orval_aruba    = nsa.Network('Aruba',   nsa.NetworkServiceAgent('Aruba-OpenNSA', OPENNSA_SERVICE))
    provider_martinique     = nsa.Network('Martinique', nsa.NetworkServiceAgent('Martinique-DynamicKL', DYNAMICKL_SERVICE))

    provider = provider_local_aruba
    #provider = provider_orval_aruba
    #provider = provider_martinique

    #source_stp      = nsa.STP('Aruba', 'Ashley' )
    source_stp      = nsa.STP('Aruba', 'A1' )
    #source_stp      = nsa.STP('Aruba', 'Axel' )
    dest_stp        = nsa.STP('Aruba', 'A2')
    #source_stp      = nsa.STP('Martinique', 'M1')
    #dest_stp        = nsa.STP('Martinique', 'M3')

    start_time = datetime.datetime.utcfromtimestamp(time.time() + 20 ).isoformat().rsplit('.',1)[0] + 'Z'
    end_time   = datetime.datetime.utcfromtimestamp(time.time() + 120 ).isoformat().rsplit('.',1)[0] + 'Z'
    #start_time, end_time = end_time, start_time

    bwp = nsa.BandwidthParameters(1000)
    #service_params  = nsa.ServiceParameters('2011-09-01T08:56:00Z', '2011-10-01T08:56:00Z' , source_stp, dest_stp, bwp)
    service_params  = nsa.ServiceParameters(start_time, end_time, source_stp, dest_stp, bandwidth=bwp)
    global_reservation_id = 'gid-%i'  % random.randrange(100,999)
    connection_id         = 'conn-%i' % random.randrange(100,999)

    print "Connection id", connection_id

    r = yield client.reservation(client_nsa, provider.nsa, None, global_reservation_id, 'Test Connection', connection_id, service_params)
    print "Reservation created. Connection ID:", connection_id

    qr = yield client.query(client_nsa, provider.nsa, None, "Summary", connection_ids = [ connection_id ] )
    print "State", qr.queryConfirmed.reservationSummary[0].connectionState

    _ = yield client.provision(client_nsa, provider.nsa, None, connection_id)
    print "Provision made"

    qr = yield client.query(client_nsa, provider.nsa, None, "Summary", connection_ids = [ connection_id ] )
    print "State", qr.queryConfirmed.reservationSummary[0].connectionState

    _ = yield client.release(client_nsa, provider.nsa, None, connection_id)
    print "Provision released"

    qr = yield client.query(client_nsa, provider.nsa, None, "Summary", connection_ids = [ connection_id ] )
    print "State", qr.queryConfirmed.reservationSummary[0].connectionState

    _ = yield client.terminate(client_nsa, provider.nsa, None, connection_id)
    print "Reservation terminated"

    r = yield client.query(client_nsa, provider.nsa, None, "Summary", connection_ids = [ connection_id ] )
    print "State", r.queryConfirmed.reservationSummary[0].connectionState



def main():

    d = defer.maybeDeferred(doMain)

    def p(failure):
        failure.printTraceback()

    d.addErrback(p)
    d.addBoth(lambda _ : reactor.stop() )
    return d



if __name__ == '__main__':
    reactor.callWhenRunning(main)
    reactor.run()

