#!/usr/bin/env python

import uuid, random

from twisted.internet import reactor, defer

from opennsa import nsa, setup
from opennsa.protocols.jsonrpc import jsonrpc



@defer.inlineCallbacks
def doMain():

    print 'OpenNSA test client'

    HOST, PORT = 'localhost', 4810

    client, service, factory  = setup.createClient()

    reactor.listenTCP(PORT, factory)

    #client = jsonrpc.JSONRPCNSIClient('localhost', 4810)

    client_nsa      = nsa.NetworkServiceAgent('nsa://%s:%s' % (HOST, PORT))

    provider_net    = nsa.Network('B', nsa.NetworkServiceAgent('nsa://localhost:4322') )
    #provider_net    = nsa.Network('E', nsa.NetworkServiceAgent('nsa://localhost:4325') )

    #source_stp      = nsa.STP('B', 'B1' )
    source_stp      = nsa.STP('A', 'A1' )
    dest_stp        = nsa.STP('E', 'E1')
    #dest_stp        = nsa.STP('D', 'D1')
    service_params  = nsa.ServiceParameters('', '', source_stp, dest_stp)

    global_reservation_id = uuid.uuid1().hex
    conn_id = 'cli-ccid' + ''.join( [ str(int(random.random() * 10)) for _ in range(4) ] )
    print "Connection id", conn_id

#    _ = yield client.query(client_nsa, provider_net.nsa, None, None)

    rd = service.addReservation(provider_net.nsa, conn_id)

    r = yield client.reserve(client_nsa, provider_net.nsa, None, global_reservation_id, 'Test Connection', conn_id, service_params)
    print "Reservation issued", r
    r = yield rd
    print "Reservation created", r


    _ = yield client.query(client_nsa, provider_net.nsa, None, None)

    _ = yield client.provision(client_nsa, provider_net.nsa, None, conn_id)
    print "Provision made"

    _ = yield client.query(client_nsa, provider_net.nsa, None, None)

    _ = yield client.releaseProvision(client_nsa, provider_net.nsa, None, conn_id)
    print "Provision released"

    _ = yield client.query(client_nsa, provider_net.nsa, None, None)

    _ = yield client.terminateReservation(client_nsa, provider_net.nsa, None, conn_id)
    print "Reservation cancelled"



def main():

    d = defer.maybeDeferred(doMain)

    def p(failure):
        print failure

    d.addErrback(p)
    d.addBoth(lambda _ : reactor.stop() )
    return d



if __name__ == '__main__':
    reactor.callWhenRunning(main)
    reactor.run()

