#!/usr/bin/env python

import sys



while True:

    line = sys.stdin.readline()

    line = line.strip()
    line = line.replace('<', '&lt;').replace('>', '&gt;')
    line = line.replace('  ', '&nbsp;')

    if 'DUDBackend' in line:
        color = 'ForestGreen'
    elif 'NSIService' in line:
        color = 'blue'
    elif 'error' in line.lower():
        color = 'red'
    elif 'ConnectionServiceResource' in line or 'TwistedSUDS' in line:
        color = 'maroon'
    else:
        color = 'black'

    line = '<tt><font color="%s">' % color + line + '</font></tt><br>' + "\n"

    sys.stdout.write(line)
    sys.stdout.flush()


