#!/bin/sh

set -a # load source environment variables into scope

. env.sh

cat template.yml | envsubst > docker-compose.yml

cat opennsa.conf.template | envsubst > opennsa.conf

echo "Start OpenNSA with: docker-compose up"

