#!/bin/sh
set -e 

# Run psql on the PostgreSQL test database

container=$(cat .opennsa-test.json | jq  -r '.container')
database=$(cat .opennsa-test.json | jq  -r '.database')
user=$(cat .opennsa-test.json | jq  -r '.user')
password=$(cat .opennsa-test.json | jq  -r '.password')


docker run --rm --name opennsa-test-psql --link=$container -it -e PGPASSWORD=$password postgres:12 \
    psql -h $container -U $user $database

