#!/bin/sh
set -e

# Run a PostgreSQL database for testing

container=opennsa-test-database
database=opennsatest
user=opennsa
password=$(openssl rand -base64 18)

configfile=".opennsa-test.json"

# Start PostgreSQL

# Note: We bind the port, so it listens on 127.0.0.1 only, so no host info needed

docker run --rm --name $container -p 127.0.0.1:5432:5432 -v $PWD/datafiles/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro \
    -e POSTGRES_DB=$database -e POSTGRES_USER=$user -e POSTGRES_PASSWORD=$password postgres:12 &

echo "{
    \"container\" : \"$container\",
    \"database\"  : \"$database\",
    \"user\"      : \"$user\",
    \"password\"  : \"$password\"
}" > "$configfile"


echo
echo "Database config file: $configfile"

